name: i10n_hierarchy_generator
description: Translate a Flutter application in an easy, structured and time proven way.
version: 1.0.7
homepage: https://github.com/maexeler/i10n_hierarchy_generator


environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  path: ^1.4.1
  args: ^1.5.2

dev_dependencies:
  test: ^1.0.0
