name: i10n_hierarchy_generator
description: command-line app
version: 1.0.0
author: Max Werner <max.maexeler@gmail.com>
homepage: https://maexeler.github.io/


environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  path: ^1.4.1
  args: ^1.5.2

dev_dependencies:
  test: ^1.0.0
